server:
  port: 8080

spring:
  application:
    name: fitnessforge 

  datasource:
      url: jdbc:postgresql://localhost:5432/fitnessforge?useSSL=false&serverTimezone=UTC
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD} 
      driver-class-name: org.postgresql.Driver
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create 
