server:
  port: 8080

spring:
  application:
    name: fitnessforge 

  datasource:
      url: jdbc:postgresql://localhost:5432/fitnessforge
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD} 
      driver-class-name: org.postgresql.Driver
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        # update: will use the existing database and data.
        # create: will delete all the existing database and tables and will start fresh
        ddl-auto: update 
      show-sql: true
      properties:
        hibernate:
          format-sql: true
