name: Generate and Deploy Javadocs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the repository
        uses: actions/checkout@v2

      # Step 2: Set up Java (you can specify the version if needed)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Generate Javadocs
      - name: Generate Javadocs
        run: |
          mkdir -p javadocs
          javadoc -d javadocs -sourcepath src/main/java -subpackages com.fitnessforge

      # Step 4: Deploy to GitHub Pages
      - name: Deploy Javadocs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: javadocs
